function onCreate()
  makeAnimatedLuaSprite('bg','studioRemix',-300,0)
  addAnimationByPrefix('bg','idle','entire',24,true)
  objectPlayAnimation('bg','idle',true)
  makeAnimatedLuaSprite('mom','momRemix',850,100)
  addAnimationByPrefix('mom','idle','mom bop',24,true)
  objectPlayAnimation('mom','idle',true)
  makeAnimatedLuaSprite('imp','impRemix',-150,250)
  scaleObject('imp',0.7,0.7)
  addAnimationByPrefix('imp','idle','imp',24,true)
  objectPlayAnimation('imp','idle',true)
  makeAnimatedLuaSprite('gf','gfRemix',50,250)
  addAnimationByPrefix('gf','idle','gf',24,true)
  objectPlayAnimation('gf','idle',true)
  makeLuaSprite('chair','chairStudio',800,500)
  addLuaSprite('bg',false)
  addLuaSprite('mom',false)
  addLuaSprite('gf',false)
  addLuaSprite('imp',false)
  addLuaSprite('chair',false)
  close(true);
  end